CREATE DATABASE ex10;
USE ex10;

DROP TABLE IF EXISTS MAQUINAS_REGISTRADORAS;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS CAJEROS;
DROP TABLE IF EXISTS VENTA;

CREATE TABLE PRODUCTOS(
	codigo int PRIMARY KEY,
	nom varchar(100),
	precio int
);

CREATE TABLE CAJEROS(
	codigo int PRIMARY KEY,
	nomApels varchar(255)
);

CREATE TABLE MAQUINAS_REGISTRADORAS(
	codigo int PRIMARY KEY,
	piso int
);

CREATE TABLE VENTA(
	cajero int,
	maquina int,
	producto int,
	PRIMARY KEY (cajero,maquina,producto),
	FOREIGN KEY (cajero) REFERENCES CAJEROS(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (maquina) REFERENCES MAQUINAS_REGISTRADORAS(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (producto) REFERENCES PRODUCTOS(codigo) ON DELETE CASCADE ON UPDATE CASCADE
);