CREATE DATABASE ex11;
USE ex11;

DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS INVISTIGADORES;
DROP TABLE IF EXISTS EQUIPOS;
DROP TABLE IF EXISTS FACULTAD;

CREATE TABLE FACULTAD(
	codigo int PRIMARY KEY,
	nombre varchar(100)
);

CREATE TABLE INVISTIGADORES (
	dni varchar(8) PRIMARY KEY,
	nomApels varchar(255),
	facultad int,
	FOREIGN KEY (facultad) REFERENCES FACULTAD(codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EQUIPOS(
	numSerie char(4) PRIMARY KEY,
	nombre varchar(100),
	facultad int,
	FOREIGN KEY (facultad) REFERENCES FACULTAD(codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RESERVA(
	dni varchar(8),
	numSerie char(4),
	comienzo datetime,
	fin datetime,
	PRIMARY KEY (dni,numSerie),
	FOREIGN KEY (dni) REFERENCES INVISTIGADORES(dni) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (numSerie) REFERENCES EQUIPOS(numSerie) ON DELETE CASCADE ON UPDATE CASCADE
);